apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: abhishek/comment:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  type: ClusterIP #this is optional as it is default
  selector:
    app: comments-bus
  ports:
    - name: comments-bus
      protocol: TCP
      port: 4001 #this is Cluster port service port
      targetPort: 4001 #this is the actual port on which our service is running

