apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: abhishek/moderation:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  type: ClusterIP #this is optional as it is default
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003 #this is Cluster port service port
      targetPort: 4003 #this is the actual port on which our service is running

