apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: abhishek/posts:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  type: ClusterIP #this is optional as it is default
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #this is Cluster port service port
      targetPort: 4000 #this is the actual port on which our service is running

