apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: abhishek/query:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: ClusterIP #this is optional as it is default
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002 #this is Cluster port service port
      targetPort: 4002 #this is the actual port on which our service is running

